### ISSUE TITLE
"close" event handler should be passed a CloseEvent argument

### ISSUE THREAD

**Issue by FredKSchott** [feross/simple-websocket#22]
From https://developer.mozilla.org/en-US/docs/Web/API/WebSocket:

> onclose: An event listener to be called when the WebSocket connection's readyState changes to CLOSED. The listener receives a CloseEvent named "close".

The listener I add to the 'close' event receives no arguments. That argument is useful for checking if it was a normal/abnormal closure.

**Comment by feross** [comment]
Which information are you looking to get out of the `CloseEvent` object? I do not want to expose this object directly since the goal of this package is to mimic the Node.js `net.Socket` API as closely as possible. See the`close` event docs: https://nodejs.org/api/net.html#net_event_close_1

What if `simple-websocket` inspected the `CloseEvent` object? Then on abnormal termination, it could emit an `error` event and pass a `had_error` argument to the `close` event handler.

**Comment by FredKSchott** [comment]
That works for me, that was ultimately the information I was trying to get out of the event.

I'm no longer using this library (just went for socket.io to save time) so I'll leave the decision up to you and the current users. Thanks for the quick and thoughtful response!

**Comment by feross** [comment]
I don't have any immediate plans to work on this issue, so I'm going to close it. If you (or anyone else) wants to tackle it, I'll happily accept a PR!
